# Generated by Django 4.2.9 on 2026-03-11 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0013_auto_20260218_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='establecimiento_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Planta/Establecimiento'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='inspections.establishment', verbose_name='Planta/Establecimiento (Referencia)'),
        ),
    ]
