# Generated by Django 4.2.9 on 2026-03-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0014_inspection_establecimiento_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sample_label_text',
            field=models.CharField(
                blank=True,
                default='MUESTRA USDA',
                help_text='Texto que reemplaza MUESTRA USDA en etiquetas e impresiones',
                max_length=255,
                verbose_name='Texto Etiqueta de Muestra'
            ),
        ),
    ]
