# Generated by Django 4.2.9 on 2026-03-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0015_userprofile_sample_label_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='sample_label_text',
            field=models.CharField(blank=True, default='MUESTRA USDA', help_text='Texto que aparecerá en el adhesivo impreso para identificar este establecimiento', max_length=255, verbose_name='Texto de Etiqueta de Muestra'),
        ),
    ]
