# Generated by Django 4.2.9 on 2026-10-01 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CherryChinaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_until', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cherry_china_plan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan de Validación Cereza China',
                'verbose_name_plural': 'Planes de Validación Cereza China',
            },
        ),
        migrations.CreateModel(
            name='CherryChinaReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csg', models.CharField(blank=True, max_length=30)),
                ('csp', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('PROCESSING', 'En proceso'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PROCESSING', max_length=12)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('pdf_file', models.FileField(blank=True, upload_to='cherry_china/reports/')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cherry_china_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Informe Cereza China',
                'verbose_name_plural': 'Informes Cereza China',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at', 'status'], name='cherry_chin_user_id_2e95e1_idx')],
            },
        ),
    ]
