# Generated by Django 4.2.9 on 2026-10-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cherry_china_validation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cherrychinareport',
            name='csgs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
