# Generated by Django 4.2.9 on 2026-10-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cherry_china_validation', '0002_cherrychinareport_csgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='cherrychinareport',
            name='csps',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
