# Generated by Django 4.2.9 on 2026-10-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cherry_china_validation', '0003_cherrychinareport_csps'),
    ]

    operations = [
        migrations.AddField(
            model_name='cherrychinareport',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cherrychinareport',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cherrychinareport',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'En cola'), ('PROCESSING', 'En proceso'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PROCESSING', max_length=12),
        ),
    ]
