# Generated by Django 4.2.9 on 2026-10-06 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cherry_china_validation', '0005_cherrychinareport_pdf_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='cherrychinaplan',
            name='monthly_report_limit',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='cherrychinaplan',
            name='unlimited',
            field=models.BooleanField(default=False),
        ),
    ]
